name: deploy
kind: pipeline
type: docker

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: bash:5
  commands:
  - bash ./build.sh

- name: deploy
  image: appleboy/drone-scp
  settings:
    host:
      from_secret: host_address
    username:
      from_secret: username
    key:
      from_secret: ssh_key
    port: 22
    target: /var/www/zrui.dev
    source: build

trigger:
  branch:
  - master
  event:
  - push

