name: S3 Deploy
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3

        - name: Build
          run: bash build.sh

        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v2
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ secrets.S3_BUCKET_REGION }}

        - name: Deploy static site to S3 bucket
          run: aws s3 sync ./build/ s3://${{ secrets.BUCKET_NAME }} --delete